project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - usage.qmd
    - methodology.qmd
    - credits.qmd
  resources:
    - site/data/**

website:
  title: "RUKS Data"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: usage.qmd
        text: Usage
      - href: methodology.qmd
        text: Methodology
      - href: credits.qmd
        text: Credits

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css
